import Head from "next/head";
//import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Editor } from "@/components/Editor";
import { Box, Heading, VStack } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <Box backgroundColor="#444" color="white">
      <Head>
        <title>Frontmatter Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./images/favicon.ico" />
        <link rel="manifest" href="./manifest.json" />
      </Head>
      <Box as="main" className={styles.main}>
        <VStack gap={5}>
          <Heading>Dendron Frontmatter Generator</Heading>
          <Box>
            <Editor />
          </Box>
        </VStack>
      </Box>
    </Box>
  );
}
